### ISSUE TITLE
Last 5 books doesn't get choosed correct

### ISSUE THREAD

**Issue by yachty66** [zwacky/goodreads-profile-workflow#5]
I configured a "Last 5 Books I've Read" section but the books which appear are not actually the books which are the last 5 books but books which I read lying further in the past. What are the criterias for the algorithm for picking the last 5 books?

**Comment by zwacky** [comment]
Hey @yachty66, thanks for bringing this up. that is indeed not intentional. the sorting is comparing the string values, instead of the date values. 

I'll add an additional check for date based sorting props.

**Comment by zwacky** [comment]
new version released. you can use it with `uses: zwacky/goodreads-profile-workflow@v1.2.3`. cheers and thanks again
